       
development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: guruapp_dev1
  pool: 5
  username: developer
  password: "123456"
  host: "172.19.0.2"
  
test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: guruapp_test
  pool: 5
  username: postgres
  password: "123456"
  host: localhost