
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: guruapp_dev
  pool: 5
  username: root
  password: "Wintheday99"
  host: localhost
  
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: guruapp_test
  pool: 5
  username: root
  password: "Wintheday99"
  host: localhost