       
development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: guruapp_dev1
  pool: 5
  username: mattnickel
  password: "Wintheday99"
  host: localhost
  
test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: guruapp_test
  pool: 5
  username: mattnickel
  password: "Wintheday99"
  host: localhost